### ISSUE TITLE
URL 분리

### ISSUE THREAD

**Issue by byeon22** [PowerSupply-ES/PES-FE#9]
## Description
- 문제 푸는 페이지와 질문-답변/피드백 페이지 URL 분리 필요

## Task

- [x] route 분리
- [x] problem 페이지와 question 페이지 연결
- [x] /problem 페이지 완성
- [ ] /question 페이지 완성
